baseURL = "https://rpg-librarium.de/"
languageCode = "de-de"
defaultContentLanguage = "de"
defaultContentLang = "de"
title = "RPG Librarium Aachen"
theme = "ananke"
#relativeUrls = true
pluralizeListTitles = false
[menu]
    [[menu.main]]
        identifier = "veranstaltungen"
        name = "Veranstaltungen"
        weight = 300
        url = "/events/"

[params]
custom_css = ["css/librarium.css"]

[taxonomies]
category = "categories"

[sitemap]
#  changefreq = "monthly"
#  priority = 0.5
filename = "sitemap.xml"
