baseURL = "https://rpg-librarium.de/"
languageCode = "de-de"
defaultContentLanguage = "de"
defaultContentLang = "de"
title = "RPG Librarium Aachen"
theme = "ananke"
#relativeUrls = true
pluralizeListTitles = false
[menu]
    [[menu.main]]
        identifier = "veranstaltungen"
        name = "Veranstaltungen"
        weight = 300
        url = "/events/"
    [[menu.main]]
        identifier = "liberation"
        name = "Bücherverwaltungᴮᴱᵀᴬ"
        weight = 500
        url = "https://liberation.rpg-librarium.de/"

[params]
custom_css = ["css/librarium.css", "source-sans/source-sans-3.css"]
body_classes = "source-sans"

[taxonomies]
category = "categories"

[sitemap]
#  changefreq = "monthly"
#  priority = 0.5
filename = "sitemap.xml"
